name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.24
        uses: actions/setup-node@v1
        with:
          node-version: 10.24
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Testing with coverage
        run: npm run test:coverage
